SELECT DISTINCT CONCEPT_ID,
	CAST(CONCEPT_SYNONYM_NAME AS VARCHAR(1000)) CONCEPT_SYNONYM_NAME
FROM @vocabulary_database_schema.concept_synonym
WHERE CONCEPT_ID IN (@concept_id_list)

UNION

SELECT DISTINCT CONCEPT_ID,
	CAST(CONCEPT_NAME AS VARCHAR(1000)) CONCEPT_SYNONYM_NAME
FROM @vocabulary_database_schema.concept
WHERE CONCEPT_ID IN (@concept_id_list);