#!/usr/bin/perl

open(R_VERSION, "grep 'Version' DESCRIPTION |");
$version = <R_VERSION>;
close(R_VERSION);

$version =~ /(\d+)\.(\d+)\.(\d+)/;
$r_major = $1;
$r_minor = $2;
$r_mod = $3;

$version = "v$r_major.$r_minor.$r_mod";
print($version);