# Copyright 2019 Observational Health Data Sciences and Informatics
#
# This file is part of StudyDiagnostics
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' @title
#' Generate stability plots
#' 
#' @description
#' Characterizes the incidence proportion of a phenotype as a time series visualization
#'
#' @details
#' Generates time series plots of the incidence proportion per 1000 persons of phenotype
#' entry by year, by year and 10-year age group, by year and gender, and by year and
#' 10-year age group and gender
#'
#' @return
#' A list of 4 gg objects generated by the ggplot2 package with option to save as 1 *.rds
#' file and 4 png files.
#'
#' @param ipData   Incidence proportion time series data for plotting generated using
#'                 \code{\link{GetIncidenceProportionData function}}.
#' @param panel    Create trellis panels by gender or by age? select "age" or "gender", defaults to "age"
#' @param fileName Optional: directory and filename of plot to be saved
#'
#' @export
generateStabilityPlots <- function(ipData,
                                   panel = "age",
                                   restrictToFullAgeData = FALSE,
                                   workFolder = NULL) {
  
  # stratified by year
  ipYearData <- ipData$ipYearData
  ipYearPlot <- ggplot2::ggplot(data = ipYearData,
                                ggplot2::aes(x = INDEX_YEAR, y = IP_1000P, group = 1)) +
    ggplot2::geom_line(ggplot2::aes(color = "red"), size = 1.25) +
    ggplot2::xlab("Year") +
    ggplot2::ylab("Incidence proportion (/1000 persons)") +
    ggplot2::theme(legend.position = "none",
                   axis.text.x = ggplot2::element_text(angle = 90))

  # stratified by year, age
  ipYearAgeData <- ipData$ipYearAgeData
  if (restrictToFullAgeData) {
    ipYearAgeData <- useFullData(ipYearAgeData)
  }
  if (panel == "age") {
    width <- 12
    ipYearAgePlot <- ggplot2::ggplot(data = ipYearAgeData,
                                     ggplot2::aes(x = INDEX_YEAR, y = IP_1000P, group = 1)) +
      ggplot2::geom_line(ggplot2::aes(color = "red"), size = 1.25) +
      ggplot2::facet_grid(. ~ AGE_GROUP_10Y) +
      ggplot2::xlab("Year") +
      ggplot2::ylab("Incidence proportion (/1000 persons)") +
      ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, size = 6),
                     legend.position = "none")
  }
  if (panel == "gender") {
    width <- 6
    ipYearAgePlot <- ggplot2::ggplot(data = ipYearAgeData,
                                     ggplot2::aes(x = INDEX_YEAR, y = IP_1000P, group = AGE_GROUP_10Y)) +
      ggplot2::geom_line(ggplot2::aes(color = AGE_GROUP_10Y), size = 1.25) +
      ggplot2::xlab("Year") +
      ggplot2::ylab("Incidence proportion (/1000 persons)") +
      ggplot2::labs(color = "Age (years)") +
      ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90))
  }

  # stratified by year, gender
  ipYearGenderData <- ipData$ipYearGenderData
  ipYearGenderPlot <- ggplot2::ggplot(data = ipYearGenderData,
                                      ggplot2::aes(x = INDEX_YEAR, y = IP_1000P, group = GENDER)) +
    ggplot2::geom_line(ggplot2::aes(color = GENDER), size = 1.25) +
    ggplot2::xlab("Year") +
    ggplot2::ylab("Incidence proportion (/1000 persons)") +
    ggplot2::labs(color = "Gender") +
    ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90))

  # stratified by year, age, gender
  ipYearAgeGenderData <- ipData$ipYearAgeGenderData
  if (restrictToFullAgeData) {
    ipYearAgeGenderData <- useFullData(ipYearAgeGenderData)
  }
  if (panel == "age") {
    ipYearAgeGenderPlot <- ggplot2::ggplot(data = ipYearAgeGenderData,
                                           ggplot2::aes(x = INDEX_YEAR, y = IP_1000P, group = GENDER)) +
      ggplot2::geom_line(ggplot2::aes(color = GENDER),  size = 1.25) +
      ggplot2::facet_grid(. ~ AGE_GROUP_10Y) +
      ggplot2::xlab("Year") +
      ggplot2::ylab("Incidence proportion (/1000 persons)") +
      ggplot2::labs(color = "Gender") +
      ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90, size = 6))
  }
  if (panel == "gender") {
    ipYearAgeGenderPlot <- ggplot2::ggplot(data = ipYearAgeGenderData,
                                           ggplot2::aes(x = INDEX_YEAR, y = IP_1000P, group = AGE_GROUP_10Y)) +
      ggplot2::geom_line(ggplot2::aes(color = AGE_GROUP_10Y),  size = 1.25) +
      ggplot2::facet_grid(. ~ GENDER) +
      ggplot2::xlab("Year") +
      ggplot2::ylab("Incidence proportion (/1000 persons)") +
      ggplot2::labs(color = "Age (years)") +
      ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 90))
  }

  ipPlotList <- list(ipYearPlot = ipYearPlot,
                     ipYearAgePlot = ipYearAgePlot,
                     ipYearGenderPlot = ipYearGenderPlot,
                     ipYearAgeGenderPlot = ipYearAgeGenderPlot)
  if (!is.null(workFolder)) {
    if (!file.exists(workFolder)) {
      dir.create(workFolder, recursive = TRUE)
    }
    saveRDS(ipPlotList, file.path(workFolder, "ipPlots.rds"))
    ggplot2::ggsave(file.path(workFolder, "ipYearPlot.png"), ipYearPlot, width = 6, height = 4.5, dpi = 400)
    ggplot2::ggsave(file.path(workFolder, "ipYearAgePlot.png"), ipYearAgePlot, width = width, height = 4.5, dpi = 400)
    ggplot2::ggsave(file.path(workFolder, "ipYearGenderPlot.png"), ipYearGenderPlot, width = 6, height = 4.5, dpi = 400)
    ggplot2::ggsave(file.path(workFolder, "ipYearAgeGenderPlot.png"), ipYearAgeGenderPlot, width = 12, height = 4.5, dpi = 400)
  }
  return(ipPlotList)
}

useFullData <- function(df) {
  yearList <- list()
  for (year in unique(df$INDEX_YEAR)) {
    yearList[[length(yearList) + 1]] <- unique(df$AGE_GROUP_10Y[df$INDEX_YEAR == year])
  }
  ageGroups <- Reduce(intersect, yearList)
  df <- df[df$AGE_GROUP_10Y %in% ageGroups, ]
  return(df)
}
